"""add allowed referers

Revision ID: 591f8ecd11bc
Revises: 15a4b499575f
Create Date: 2018-01-30 23:23:27.531857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591f8ecd11bc'
down_revision = '15a4b499575f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('allowed_referers', sa.Text(), nullable=True))
    op.alter_column('api_keys', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('api_keys', 'allowed_referers')
    # ### end Alembic commands ###
